# Generated by Django 5.2.17 on 2026-08-07 16:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LSAProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(db_index=True, max_length=255)),
                ("bio", models.TextField(blank=True)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["full_name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 0), ("rating__lte", 5)),
                        name="lsa_rating_between_zero_and_five",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("BOOKED", "Booked"),
                            ("BLOCKED", "Blocked"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "lsa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="lsas.lsaprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["lsa", "date"], name="availability_lsa_date_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("start_time__lt", models.F("end_time"))),
                        name="availability_start_before_end",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LSASkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("experience_years", models.PositiveIntegerField(default=0)),
                (
                    "lsa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lsa_skills",
                        to="lsas.lsaprofile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lsa_skills",
                        to="lsas.skill",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lsa", "skill"), name="unique_lsa_skill"
                    )
                ],
            },
        ),
    ]
