# Generated by Django 5.2.17 on 2026-08-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("lsas", "0001_initial"),
        ("parents", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("availability",), name="one_booking_per_availability"
            ),
        ),
    ]
